default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5
  username: postgres
  password: benw

development:
  <<: *default
  database: socialpostsapp_development
  username: postgres
  password: benw
  port: 5432
  host: 127.0.0.1

  # server: 127.0.0.1

test:
  <<: *default
  database: socialpostsapp_test

#
production:
  <<: *default
  database: socialpostsapp_production
  username: concepti_app
  password: <%= ENV['SOCIALPOSTSAPP_DATABASE_PASSWORD'] %>
